dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - smartcontractkit/chainlink-brownie-contracts@0.4.0

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"

dotenv: .env

networks:
  rinkeby:
    #eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    vrf_coordinator: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    verify: True
  mainnet-fork:
    #eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  publisher_key: ${PUBLISH_PVK}
  personal_key: ${PERSONAL_PVK}
  other1_key: ${OTHER1_PVK}
  other2_key: ${OTHER2_PVK}
